title: Neekaru Home
description: A vintage postcard style blog

# Custom domain and URL settings
url: "https://neekarublog.github.io"  # Base hostname and protocol for your site
baseurl: "https://neekarublog.github.io"      # Base URL (the repository name in this case)

# Permalink structure
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown

# Plugins for extra functionality
plugins:
  - jekyll-feed
