name: Convert post.txt to Markdown

on:
  push:
    paths:
      - post.txt  # Trigger action when post.txt is modified

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Check if commit message have "post: "
      if: contains(github.event.commits[0].message, 'post: ')
      run: |
        if [ -f post.txt ]; then
          node convertPost.js post.txt
          git add _posts
          git commit -m "Add new post(s) from post.txt"
          git push origin main
        fi

    - name: Remove post.txt
      run: |
        git rm post.txt || true  # Ignore errors if file doesn't exist
        git commit -m "Remove post.txt after conversion"
        git push origin main

