name: Convert post.txt to Markdown and Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main
    paths:
      - post.txt
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "kang post"
          git config --global user.email "kangpost@roja.com"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Process post.txt and commit changes
        run: |
          if [ -f post.txt ]; then
            # Convert post.txt to markdown
            node convertPost.js post.txt
            
            # Stage the new posts
            git add _posts/
            git commit -m "Add new post(s) from post.txt" || true
            
            # Remove and commit post.txt
            git rm post.txt
            git commit -m "Remove post.txt after conversion" || true
            
            # Push all changes
            git push origin main
          fi

  jekyll_build:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Build the site with specific Jekyll version
        run: |
          export JEKYLL_VERSION=4.3.3
          docker run --rm \
            --volume="${{ github.workspace }}:/srv/jekyll:Z" \
            jvconseil/jekyll-docker:$JEKYLL_VERSION \
            jekyll build --future

  deploy:
    runs-on: ubuntu-latest
    needs: jekyll_build
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy_pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
